splash = false

preload = /home/trevor/Pictures/wallpaper/BladeRunner2049-46.jpeg

wallpaper = DP-1,/home/trevor/Pictures/wallpaper/BladeRunner2049-46.jpeg
wallpaper = HDMI-A-1,/home/trevor/Pictures/wallpaper/BladeRunner2049-46.jpeg
