general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    contrast = 1.2
    brightness = 0.75
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -80
    halign = center
    valign = center

    outer_color = rgba(255, 255, 255, 0.15)
    inner_color = rgba(0, 0, 0, 0.4)
    font_color = rgba(255, 255, 255, 0.9)

    placeholder_text = enter password...
}
